package nl.han.ica.veiligveilen.server.model.dataclasses;

import java.io.Serial;
import java.io.Serializable;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Type;

/**
 * The dataclass for the client in the database.
 */
@Entity(name = "clients")
public class Client implements Serializable {
	@Serial
	private static final long serialVersionUID = 7997427218594445248L;

	@Id
	@Type(type = "uuid-char")
	@Size(max = 36)
	@Column(name = "client_id", nullable = false)
	private UUID clientId;

	/**
	 * The constructor.
	 * @param clientId A UUID. Will be automatically generated by the client on the first startup.
	 */
	public Client(UUID clientId) {
		this.clientId = clientId;
	}

	public Client() {

	}

	public UUID getClientId() {
		return this.clientId;
	}

	public void setClientId(UUID clientId) {
		this.clientId = clientId;
	}
}
