package nl.han.ica.veiligveilen.server.model.dataclasses;

import java.math.BigDecimal;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.validation.constraints.Size;
import org.hibernate.annotations.Type;


/**
 * Dataclass for Lot (Kavel).
 */
@Entity(name = "lot")
public class Lot {

	@Id
	@Type(type = "uuid-char")
	@Size(max = 36)
	@Column(name = "lot_id", nullable = false)
	private UUID lotId;

	@Column(name = "lot_nr", nullable = false, unique = true)
	private int lotNr;

	@OneToOne
	@JoinColumn(name = "auction_id")
	private Auction auction;

	@Size(max = 512)
	@Column(name = "lot_name", nullable = false)
	private String lotName;

	@Column(name = "reserve_price", nullable = false)
	private BigDecimal reservePrice;


	@Column(name = "description")
	private String description;

	@OneToOne
	@JoinColumn(name = "seller_id", nullable = false)
	private Seller seller;

	public Lot() {

	}

	/**
	 * The constructor.
	 * @param lotId A UUID. Generated when inserted into the database.
	 * @param lotNr An int. An identifier of the lots of an auction that isn't the ID. Will be automatically
	 *              generated by the database.
	 * @param auction the auction of which this lot is part of.
	 * @param lotName A String. The name of the lot.
	 * @param reservePrice A BigDecimal. The reserve price of the lot.
	 * @param description A String. The description of the lot.
	 * @param seller A seller object.
	 */
	public Lot(UUID lotId, int lotNr, Auction auction, String lotName, BigDecimal reservePrice,
				String description, Seller seller) {
		this.lotId = lotId;
		this.lotNr = lotNr;
		this.auction = auction;
		this.lotName = lotName;
		this.reservePrice = reservePrice;
		this.description = description;
		this.seller = seller;
	}

	public UUID getLotId() {
		return this.lotId;
	}

	public int getLotNr() {
		return this.lotNr;
	}

	public Auction getAuction() {
		return this.auction;
	}

	public String getLotName() {
		return this.lotName;
	}

	public BigDecimal getReservePrice() {
		return this.reservePrice;
	}

	public String getDescription() {
		return this.description;
	}

	public Seller getSeller() {
		return this.seller;
	}

	public void setLotID(UUID lotId) {
		this.lotId = lotId;
	}
}
